# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 40038bf502f4f590b71126749c021b1f26bd72f4a261623779c8442eecc8d51cd0261e4bc2e3c0607618139d8778e51e2a1c7211fd2d9b2c37e3f87a6a455977

test:
  secret_key_base: e33aacd0be3bb5b694da5927d5734cda1d241339d0ef35f61abbae5e7f4f027f9362a6724e969f689b18d773dac9da85481635c781308366e8bc2c90e6aaba56

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
